# Generated by Django 5.1 on 2024-09-05 00:40

import apps.projects.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bot name")),
                ("description", models.TextField(verbose_name="Description")),
                ("version", models.TextField(default="1.0", max_length=10)),
                ("prompt", models.TextField(verbose_name="Model prompt")),
                (
                    "aimodel",
                    models.CharField(
                        choices=[("gemini-flash-1.5", "Gemini Flash 1.5")],
                        max_length=20,
                        verbose_name="AI model",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=apps.projects.models.default_bot_config,
                        verbose_name="LLM options",
                    ),
                ),
                (
                    "end_string",
                    models.CharField(
                        default="ENDOFINTERVIEW",
                        max_length=100,
                        verbose_name="Termination string",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("test", "Testing"),
                            ("live", "Live"),
                            ("disabled", "Disabled"),
                        ],
                        default="test",
                        max_length=20,
                    ),
                ),
                (
                    "allow_public",
                    models.BooleanField(
                        default=False, verbose_name="Allow uninvited use"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Short name")),
                ("short_md", models.TextField(verbose_name="Short version")),
                ("letter_md", models.TextField(verbose_name="Letter")),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_email",
                    models.EmailField(max_length=254, verbose_name="Recipient email"),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=50, verbose_name="Recipient name"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time conversation started"
                    ),
                ),
                (
                    "has_consented",
                    models.BooleanField(
                        default=False, verbose_name="Has given informed consent"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Participant invited"),
                            ("started", "Started"),
                            ("complete", "Complete"),
                            ("test", "Test interview"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="projects.bot",
                    ),
                ),
                (
                    "consent_letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.consentletter",
                    ),
                ),
            ],
            options={
                "ordering": ["subject_name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("ai", "AI"),
                            ("researcher", "Researcher"),
                            ("subject", "Subject"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Sent at (server time)",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message text")),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.interview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("research_aims", models.TextField(blank=True, null=True)),
                ("funding", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (("can_delete_own", "Can delete own project"),),
            },
        ),
        migrations.CreateModel(
            name="InvitationEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("subject", models.CharField(max_length=200)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="projects.interview",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interview",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Dimension name"),
                ),
                ("order", models.IntegerField(verbose_name="Order")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consentletter",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_letters",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bots",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("order", models.IntegerField(verbose_name="Order")),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Enabled"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_text", models.TextField()),
                ("description", models.TextField()),
                (
                    "is_excluded",
                    models.BooleanField(
                        default=False, verbose_name="Exclude from analysis"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "interview",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.interview",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("editor", "Editor")],
                        max_length=6,
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project"], name="projects_me_project_819eb9_idx"
                    ),
                    models.Index(
                        fields=["user"], name="projects_me_user_id_3e2856_idx"
                    ),
                ],
            },
        ),
    ]
