# Generated by Django 5.1 on 2024-09-10 10:32

import apps.projects.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsentLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Short name")),
                ("short_md", models.TextField(verbose_name="Short version")),
                ("letter_md", models.TextField(verbose_name="Letter")),
            ],
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Dimension name"),
                ),
                ("order", models.IntegerField(verbose_name="Order")),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("editor", "Editor")],
                        max_length=6,
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberInvitation",
            fields=[
                (
                    "code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("editor", "Editor")],
                        max_length=6,
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("message", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.projects.models.MemberInvitation.default_expiry
                    ),
                ),
                (
                    "accepted_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("research_aims", models.TextField(blank=True, null=True)),
                ("funding", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "permissions": (("can_delete_own", "Can delete own project"),),
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("order", models.IntegerField(verbose_name="Order")),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Enabled"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(blank=None, max_length=100)),
                ("full_text", models.TextField()),
                ("description", models.TextField()),
                (
                    "is_excluded",
                    models.BooleanField(
                        default=False, verbose_name="Exclude from analysis"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bot name")),
                ("description", models.TextField(verbose_name="Description")),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("prompt", models.TextField(verbose_name="Model prompt")),
                (
                    "aimodel",
                    models.CharField(
                        choices=[("gemini-flash-1.5", "Gemini Flash 1.5")],
                        max_length=20,
                        verbose_name="AI model",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=apps.projects.models.default_bot_config,
                        verbose_name="LLM options",
                    ),
                ),
                (
                    "opening_user_statement",
                    models.CharField(
                        blank=True,
                        default="Hello",
                        max_length=100,
                        null=True,
                        verbose_name="Opening user statement",
                    ),
                ),
                (
                    "end_string",
                    models.CharField(
                        default="ENDOFINTERVIEW",
                        max_length=100,
                        verbose_name="Termination string",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("test", "Testing"),
                            ("live", "Live"),
                            ("disabled", "Disabled"),
                        ],
                        default="test",
                        max_length=20,
                    ),
                ),
                (
                    "allow_public",
                    models.BooleanField(default=False, verbose_name="Allow public use"),
                ),
                (
                    "consent_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.consentletter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifier",
                    ),
                ),
                (
                    "subject_email",
                    models.EmailField(max_length=254, verbose_name="Recipient email"),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=50, verbose_name="Recipient name"),
                ),
                (
                    "has_consented",
                    models.BooleanField(
                        default=False, verbose_name="Has given informed consent"
                    ),
                ),
                (
                    "content",
                    models.JSONField(default=list, verbose_name="Interview content"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Participant invited"),
                            ("started", "Started"),
                            ("complete", "Complete"),
                            ("test", "Test interview"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time conversation started"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last message at"
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="projects.bot",
                    ),
                ),
            ],
            options={
                "ordering": ["subject_name"],
            },
        ),
        migrations.CreateModel(
            name="InvitationEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("subject", models.CharField(max_length=200)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="projects.interview",
                    ),
                ),
            ],
        ),
    ]
