# Generated by Django 5.1 on 2024-09-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="allow_public",
            field=models.BooleanField(default=False, verbose_name="Allow public use"),
        ),
    ]
