# Generated by Django 5.1 on 2024-09-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="followup_consented",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Has given consent for followup interview",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="has_consented",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Has given informed consent",
            ),
        ),
    ]
