# Generated by Django 5.1 on 2024-08-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_membership_invitation_email_alter_membership_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='invitation_name',
            field=models.CharField(default='bob', max_length=100),
            preserve_default=False,
        ),
    ]
