# Generated by Django 5.1 on 2024-09-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_bot_allow_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="subject_name",
            field=models.CharField(blank=None, default="", max_length=100),
            preserve_default=False,
        ),
    ]
