# Generated by Django 5.1 on 2024-09-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_interview_followup_consented_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
    ]
