# Generated by Django 5.1 on 2024-09-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_transcript_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="version",
            field=models.CharField(default="1.0", max_length=10),
        ),
    ]
