# Generated by Django 5.1 on 2024-08-29 00:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_rename_changed_at_membership_last_modified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="invitation_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
