# Generated by Django 5.1 on 2024-09-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_interview_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="ip_address",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="content",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Interview content"
            ),
        ),
    ]
