# Generated by Django 5.1 on 2024-09-05 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_bot_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="consent_letter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.consentletter",
            ),
        ),
    ]
