# Generated by Django 5.1 on 2024-09-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_interview_ip_address_alter_interview_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="aimodel",
            field=models.CharField(
                choices=[("gemini-1.5-flash", "Gemini Flash 1.5")],
                max_length=20,
                verbose_name="AI model",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="subject_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Recipient email"
            ),
        ),
    ]
