# Generated by Django 5.1 on 2024-09-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_bot_consent_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="opening_user_statement",
            field=models.CharField(
                blank=True,
                default="Hello",
                max_length=100,
                null=True,
                verbose_name="Opening user statement",
            ),
        ),
    ]
