# Generated by Django 5.1 on 2024-09-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_bot_opening_user_statement"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last message at"
            ),
        ),
    ]
