# Generated by Django 5.1 on 2024-09-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_bot_aimodel_alter_interview_subject_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="caution",
            field=models.CharField(
                default="Please do not disclose sensitive information", max_length=200
            ),
        ),
    ]
