# Generated by Django 5.1 on 2024-08-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_member_delete_membership_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"permissions": (("can_delete_own", "Can delete owned project"),)},
        ),
    ]
