# Generated by Django 5.1 on 2024-09-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_interview_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["sent_at"]},
        ),
        migrations.RemoveField(
            model_name="interview",
            name="consent_letter",
        ),
        migrations.AlterField(
            model_name="message",
            name="interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="projects.interview",
            ),
        ),
    ]
