# Generated by Django 5.1 on 2024-09-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_bot_caution"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="config",
            field=models.JSONField(default=dict, verbose_name="Model config"),
        ),
        migrations.AddField(
            model_name="interview",
            name="is_test",
            field=models.BooleanField(
                default=False, verbose_name="This is a test interview"
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="prompt",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Model prompt"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Participant invited"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                ],
                max_length=10,
            ),
        ),
    ]
