# Generated by Django 5.1 on 2024-09-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0008_interview_config_interview_is_test_interview_prompt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="aimodel",
            field=models.CharField(
                choices=[("gemini-1.5-flash", "Gemini Flash 1.5")],
                default="",
                max_length=20,
                verbose_name="AI model",
            ),
            preserve_default=False,
        ),
    ]
