# Generated by Django 5.1 on 2024-09-05 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                verbose_name="Identifier",
            ),
        ),
    ]
