# Generated by Django 5.1 on 2024-09-04 10:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_options_alter_member_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.IntegerField(default=1)),
                ("prompt", models.TextField(verbose_name="Model prompt")),
                ("engine", models.CharField(max_length=100, verbose_name="AI engine")),
                ("config", models.JSONField(verbose_name="LLM options")),
                (
                    "end_string",
                    models.CharField(max_length=100, verbose_name="Termination string"),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "allow_public",
                    models.BooleanField(
                        default=False, verbose_name="Allow uninvited use"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_email",
                    models.EmailField(max_length=254, verbose_name="Recipient email"),
                ),
                ("subject_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time conversation started"
                    ),
                ),
                (
                    "has_consented",
                    models.BooleanField(
                        default=False, verbose_name="Has given informed consent"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Participant invited"),
                            ("started", "Started"),
                            ("complete", "Complete"),
                            ("test", "Test interview"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("ai", "AI"),
                            ("researcher", "Researcher"),
                            ("subject", "Subject"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Sent at (server time)",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message text")),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.interview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("order", models.IntegerField(verbose_name="Order")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
