# Generated by Django 5.1 on 2024-09-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_interview_aimodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="end_string",
            field=models.CharField(
                default="ENDOFINTERVIEW",
                max_length=100,
                verbose_name="Termination string",
            ),
        ),
    ]
