# Generated by Django 5.1 on 2024-09-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_alter_interview_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="content",
            field=models.JSONField(default=list, verbose_name="Interview content"),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
