# Generated by Django 5.1 on 2024-09-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_dimension"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="Enabled"),
        ),
    ]
