# Generated by Django 5.1 on 2024-09-04 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_question_is_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="bot",
            name="engine",
        ),
        migrations.AddField(
            model_name="bot",
            name="aimodel",
            field=models.CharField(
                choices=[("gemini-flash-1.5", "Gemini Flash 1.5")],
                default="gemini-flash-1.5",
                max_length=20,
                verbose_name="AI model",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="ConsentLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identifier",
                    ),
                ),
                ("markdown", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
