# Generated by Django 5.1 on 2024-09-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_remove_transcript_updated_at_bot_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interview",
            options={"ordering": ["-updated_at"]},
        ),
    ]
