# Generated by Django 5.1 on 2024-09-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_interview_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="attributes",
            field=models.JSONField(default=dict, verbose_name="Additional attributes"),
        ),
    ]
