# Generated by Django 5.1 on 2024-09-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0012_alter_question_options_remove_bot_engine_bot_aimodel_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Bot name"),
        ),
        migrations.AlterField(
            model_name="bot",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bots",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="status",
            field=models.CharField(
                choices=[
                    ("test", "Testing"),
                    ("live", "Live"),
                    ("disabled", "Disabled"),
                ],
                default="test",
                max_length=20,
            ),
        ),
    ]
