# Generated by Django 5.1 on 2024-09-04 20:31

import apps.projects.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_bot_name_alter_bot_project_alter_bot_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interview",
            options={"ordering": ["subject_name"]},
        ),
        migrations.RemoveField(
            model_name="consentletter",
            name="markdown",
        ),
        migrations.AddField(
            model_name="consentletter",
            name="letter_md",
            field=models.TextField(default="", verbose_name="Letter"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consentletter",
            name="name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Short name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consentletter",
            name="short_md",
            field=models.TextField(default="", verbose_name="Short version"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interview",
            name="bot",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="projects.bot",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interview",
            name="consent_letter",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.consentletter",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bot",
            name="config",
            field=models.JSONField(
                default=apps.projects.models.default_bot_config,
                verbose_name="LLM options",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="end_string",
            field=models.CharField(
                default="ENDOFINTERVIEW",
                max_length=100,
                verbose_name="Termination string",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="InvitationEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("subject", models.CharField(max_length=200)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.interview",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
