# Generated by Django 5.1 on 2024-09-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_interview_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="bot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interviews",
                to="projects.bot",
            ),
        ),
    ]
