# Generated by Django 5.1 on 2024-09-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_alter_interview_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
            preserve_default=False,
        ),
    ]
