# Generated by Django 5.1 on 2024-10-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_bot_deleted_at_alter_interview_bot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transcript",
            old_name="last_modified_at",
            new_name="updated_at",
        ),
    ]
