# Generated by Django 5.1 on 2024-11-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_rename_last_modified_at_transcript_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transcript",
            old_name="subject_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="transcript",
            name="description",
        ),
        migrations.RemoveField(
            model_name="transcript",
            name="full_text",
        ),
        migrations.RemoveField(
            model_name="transcript",
            name="is_excluded",
        ),
        migrations.AddField(
            model_name="transcript",
            name="content",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="interview",
            name="attributes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Additional attributes"
            ),
        ),
    ]
