# Generated by Django 5.1 on 2024-11-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_case_record_delete_transcript"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("discrete", "Discrete-valued"),
                            ("continuous", "Continuous-valued"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField()),
                ("display_in_table", models.BooleanField(default=True)),
                ("include_for_llm", models.BooleanField(default=True)),
                ("display_with_name", models.BooleanField(default=False)),
                ("display_properties", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name="case",
            name="name",
        ),
        migrations.AddField(
            model_name="case",
            name="pseudonym",
            field=models.CharField(blank=None, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="real_name",
            field=models.CharField(
                blank=None, default="", max_length=200, verbose_name="Real name"
            ),
            preserve_default=False,
        ),
    ]
