# Generated by Django 5.1 on 2024-11-22 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_case_record_delete_transcript"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="name",
        ),
        migrations.AddField(
            model_name="case",
            name="pseudonym",
            field=models.CharField(blank=None, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="real_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="Real name",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.IntegerField(default=100, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="record",
            name="content",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveField(
            model_name="record",
            name="id"
        ),
        migrations.AddField(
            model_name="record",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("ai_chat", "AI chat"),
                    ("manual_transcript", "Transcript"),
                    ("note", "Note"),
                ],
                max_length=20,
                verbose_name="Record type",
            ),
        ),
        migrations.CreateModel(
            name="CaseAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("discrete", "Discrete-valued"),
                            ("continuous", "Continuous-valued"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField()),
                ("display_in_table", models.BooleanField(default=True)),
                ("include_for_llm", models.BooleanField(default=True)),
                ("display_with_name", models.BooleanField(default=False)),
                ("display_properties", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_attributes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("name", "project")},
            },
        ),
    ]
