# Generated by Django 5.1 on 2024-11-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_case_record_delete_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
