# Generated by Django 5.1 on 2024-11-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_caseattribute_remove_case_name_case_pseudonym_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="real_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="Real name",
            ),
        ),
    ]
