# Generated by Django 5.1 on 2024-11-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_remove_case_name_case_pseudonym_case_real_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="description",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
