# Generated by Django 5.1 on 2024-11-17 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_case_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
