# Generated by Django 5.1 on 2024-11-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_alter_case_description_alter_case_real_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caseattribute",
            options={"ordering": ["order"]},
        ),
    ]
