# Generated by Django 5.1 on 2024-11-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_record_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="themes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
