# Generated by Django 5.1 on 2024-11-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_record_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
