# Generated by Django 5.1 on 2024-11-22 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_alter_caseattribute_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseattribute",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_attributes",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
