# Generated by Django 5.1 on 2024-11-24 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def insert_models(apps, schema_editor):
    AIModel = apps.get_model('projects', 'AIModel')
    AIModel.objects.create(name='Gemini 1.5 flash', api_name='gemini-1.5-flash', family='gemini')
    AIModel.objects.create(name='Gemini 1.5 pro', api_name='gemini-1.5-pro', family='gemini')


def delete_models(apps, schema_editor):
    AIModel = apps.get_model('projects', 'AIModel')
    for m in AIModel.objects.all():
        m.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_project_themes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("api_name", models.CharField(max_length=100)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("gpt", "OpenAI"),
                            ("anthropic", "Anthropic"),
                        ],
                        default="gemini",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.aimodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.RunPython(insert_models, delete_models),
    ]
