# Generated by Django 5.1 on 2024-11-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_aimodel_query"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="content",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
