# Generated by Django 5.1 on 2024-11-17 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_alter_case_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Identifier",
            ),
        ),
    ]
