# Generated by Django 5.1 on 2024-11-22 02:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_caseattribute_created_at_caseattribute_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseattribute",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
