# Generated by Django 5.1 on 2024-11-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_alter_query_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="scope",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="record",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("ai_chat", "AI chat"),
                    ("manual_transcript", "Other transcript"),
                    ("note", "Note"),
                ],
                max_length=20,
                verbose_name="Record type",
            ),
        ),
    ]
