# Generated by Django 5.1 on 2024-11-17 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_alter_case_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="projects.case",
            ),
        ),
    ]
