# Generated by Django 5.1 on 2024-11-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_alter_caseattribute_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("ai_chat", "AI chat"),
                    ("manual_transcript", "Transcript"),
                    ("notes", "Note"),
                ],
                max_length=20,
                verbose_name="Record type",
            ),
        ),
    ]
