# Generated by Django 5.1 on 2024-11-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_alter_record_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="deleted_at",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
