# Generated by Django 5.1 on 2025-02-15 01:49

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_query_scope_alter_record_record_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="scope",
            field=models.JSONField(
                default=apps.projects.models.default_all_record_types
            ),
        ),
    ]
