# Generated by Django 5.1 on 2026-01-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_alter_query_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="aimodel",
            field=models.CharField(
                choices=[
                    ("gemini-2.5-flash", "Gemini 2.5 Flash"),
                    ("gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite"),
                    ("gemini-2.5-pro", "Gemini 2.5 Pro"),
                    ("gemini-3-flash-preview", "Gemini 3 Flash (preview)"),
                    ("gemini-3-pro-preview", "Gemini 3 Pro (preview)"),
                ],
                max_length=50,
                verbose_name="AI model",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="aimodel",
            field=models.CharField(
                choices=[
                    ("gemini-2.5-flash", "Gemini 2.5 Flash"),
                    ("gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite"),
                    ("gemini-2.5-pro", "Gemini 2.5 Pro"),
                    ("gemini-3-flash-preview", "Gemini 3 Flash (preview)"),
                    ("gemini-3-pro-preview", "Gemini 3 Pro (preview)"),
                ],
                max_length=50,
                verbose_name="AI model",
            ),
        ),
    ]
