# Generated by Django 5.1 on 2024-11-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_case_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
