# Generated by Django 5.1 on 2026-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_alter_bot_aimodel_alter_interview_aimodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="ip_address",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
