# Generated by Django 5.1 on 2024-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_alter_case_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="attributes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
