# Generated by Django 5.1 on 2024-08-30 03:16

import apps.invitations.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_member_delete_membership_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberInvitation",
            fields=[
                (
                    "code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("role", models.CharField(max_length=6)),
                ("email", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("message", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField()),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.invitations.models.MemberInvitation.default_expiry
                    ),
                ),
                (
                    "accepted_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
