# Generated by Django 5.1 on 2024-08-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberinvitation",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
