# Generated by Django 5.1 on 2024-09-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0002_alter_memberinvitation_sent_at"),
        ("projects", "0008_alter_project_options_alter_member_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memberinvitation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="memberinvitation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_invitations",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="memberinvitation",
            name="role",
            field=models.CharField(
                choices=[("viewer", "Viewer"), ("editor", "Editor")], max_length=6
            ),
        ),
    ]
