services:
  web:
    build:
      context: .
    command:
      [
        "sh",
        "-c",
        "python manage.py collectstatic --noinput && gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 -w 4",
      ]
    env_file:
      - ./.env
    environment:
      DJANGO_ENVIRONMENT: container
      DEBUG: "False"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_NAME: monklet
      DB_USER: monklet
      DB_PASSWORD: monklet
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - redis
    ports:
      - "8765:8000"
    volumes:
      - ./logs/monklet:/var/log/monklet

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: monklet
      POSTGRES_USER: monklet
      POSTGRES_PASSWORD: monklet
    volumes:
      - monklet_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - monklet_redis_data:/data

  celery_worker:
    build:
      context: .
    command: celery -A config.celery worker --loglevel=info --concurrency=2
    env_file:
      - ./.env
    volumes:
      - ./logs/monklet:/var/log/monklet
    environment:
      DJANGO_ENVIRONMENT: container
      DEBUG: "False"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_NAME: monklet
      DB_USER: monklet
      DB_PASSWORD: monklet
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - redis

  celery_beat:
    build:
      context: .
    command: celery -A config.celery beat --loglevel=info
    env_file:
      - ./.env
    volumes:
      - ./logs/monklet:/var/log/monklet
    environment:
      DJANGO_ENVIRONMENT: container
      DEBUG: "False"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_NAME: monklet
      DB_USER: monklet
      DB_PASSWORD: monklet
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - redis

volumes:
  monklet_postgres_data:
  monklet_redis_data:
