# Generated by Django 5.1 on 2024-11-17 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, null=True, verbose_name="API token"
            ),
        ),
    ]
