GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "www-data";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO "www-data";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "www-data";

