# Generated by Django 5.1 on 2024-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enquiry",
            options={
                "verbose_name": "Web enquiry",
                "verbose_name_plural": "Web enquiries",
            },
        ),
        migrations.AddField(
            model_name="enquiry",
            name="message",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enquiry",
            name="name",
            field=models.CharField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
