from typing import Dict, Any


def backend_context(ctx: Dict[str, Any]) -> Dict[str, str]:
    ret = {
        "layout": "vertical",
        "theme": "theme-semi-dark",
        "style": "light",
        "rtl_support": False,
        "rtl_mode": False,
        "has_customizer": True,
        "display_customizer": False,
        "content_layout": "compact",
        "navbar_type": "fixed",
        "header_type": "fixed",
        "menu_fixed": True,
        "menu_collapsed": False,
        "footer_fixed": False,
        "show_dropdown_onhover": True,
        "customizer_controls": [
            "rtl",
            "style",
            "headerType",
            "contentLayout",
            "layoutCollapsed",
            "showDropdownOnHover",
            "layoutNavbarOptions",
            "themes",
        ],
        "content_navbar": True,
        "is_navbar": True,
        "is_menu": True,
        "is_footer": True,
        "navbar_detached": True,
        "header_type_class": "",
        "navbar_type_class": "layout-navbar-fixed",
        "menu_collapsed_class": "",
        "menu_fixed_class": "layout-menu-fixed",
        "footer_fixed_class": "",
        "rtl_support_value": "/rtl",
        "rtl_mode_value": "ltr",
        "text_direction_value": "ltr",
        "show_dropdown_onhover_value": "true",
        "display_customizer_class": "",
        "container_class": "container-xxl",
        "content_layout_class": "layout-compact",
        "navbar_detached_class": "navbar-detached",
        "layout_path": "layout/layout_vertical.html",
    }
    ret.update(ctx)
    return ret


def blank_context(ctx=None) -> Dict[str, str]:
    ret = {
        "layout": "blank",
        "theme": "theme-semi-dark",
        "style": "system",
        "rtl_support": False,
        "rtl_mode": False,
        "has_customizer": True,
        "display_customizer": False,
        "content_layout": "wide",
        "navbar_type": "fixed",
        "header_type": "fixed",
        "menu_fixed": True,
        "menu_collapsed": False,
        "footer_fixed": False,
        "show_dropdown_onhover": True,
        "customizer_controls": [
            "rtl",
            "style",
            "headerType",
            "contentLayout",
            "layoutCollapsed",
            "showDropdownOnHover",
            "layoutNavbarOptions",
            "themes",
        ],
        "content_navbar": True,
        "is_navbar": True,
        "is_menu": True,
        "is_footer": True,
        "navbar_detached": True,
        "header_type_class": "",
        "navbar_type_class": "layout-navbar-fixed",
        "menu_collapsed_class": "",
        "menu_fixed_class": "layout-menu-fixed",
        "footer_fixed_class": "",
        "rtl_support_value": "",
        "rtl_mode_value": "ltr",
        "text_direction_value": "ltr",
        "show_dropdown_onhover_value": "true",
        "display_customizer_class": "customizer-hide",
        "container_class": "container-fluid",
        "content_layout_class": "layout-wide",
        "navbar_detached_class": "navbar-detached",
        "layout_path": "layout/layout_blank.html",
    }
    if ctx:
        ret.update(ctx)
    return ret


def front_context(ctx=None) -> Dict[str, str]:
    ret = {
        "layout": "front",
        "theme": "theme-semi-dark",
        "style": "light",
        "rtl_support": False,
        "rtl_mode": False,
        "has_customizer": True,
        "display_customizer": False,
        "content_layout": "wide",
        "navbar_type": "fixed",
        "header_type": "fixed",
        "menu_fixed": True,
        "menu_collapsed": False,
        "footer_fixed": False,
        "show_dropdown_onhover": True,
        "customizer_controls": [
            "rtl",
            "style",
            "headerType",
            "contentLayout",
            "layoutCollapsed",
            "showDropdownOnHover",
            "layoutNavbarOptions",
            "themes",
        ],
        "content_navbar": True,
        "is_navbar": True,
        "is_menu": True,
        "is_footer": True,
        "navbar_detached": True,
        "header_type_class": "",
        "navbar_type_class": "layout-navbar-fixed",
        "menu_collapsed_class": "",
        "menu_fixed_class": "layout-menu-fixed",
        "footer_fixed_class": "",
        "rtl_support_value": "/rtl",
        "rtl_mode_value": "ltr",
        "text_direction_value": "ltr",
        "show_dropdown_onhover_value": "true",
        "display_customizer_class": "",
        "container_class": "container-fluid",
        "content_layout_class": "layout-wide",
        "navbar_detached_class": "navbar-detached",
        "layout_path": "layout/layout_front.html",
        "is_front": True,
    }
    if ctx:
        ret.update(ctx)
    return ret
